services:
  postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: youruser
      POSTGRES_PASSWORD: yourpassword
      POSTGRES_DB: yourdatabase
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  url-shortener:
    build:
      context: .
      dockerfile: ./services/url-shortener/Dockerfile
    command: sh -c "yarn migration:run && yarn run start:dev"
    volumes:
      - ./services/url-shortener:/app
      - /app/node_modules
    ports:
      - "3001:3000"
    environment:
      DATABASE_HOST: postgres
      DATABASE_PORT: 5432
      DATABASE_USERNAME: youruser
      DATABASE_PASSWORD: yourpassword
      DATABASE_NAME: yourdatabase
      JWT_SECRET: your_jwt_secret
    depends_on:
      - postgres

  auth-service:
    build:
      context: .
      dockerfile: ./services/auth-service/Dockerfile
    command: yarn run start:dev
    volumes:
      - ./services/auth-service:/app
      - /app/node_modules
    ports:
      - "3002:3000"
    environment:
      DATABASE_HOST: postgres
      DATABASE_PORT: 5432
      DATABASE_USERNAME: youruser
      DATABASE_PASSWORD: yourpassword
      DATABASE_NAME: yourdatabase
      JWT_SECRET: your_jwt_secret
    depends_on:
      - postgres

volumes:
  pgdata:
